### PR TITLE
Multiple criteria with conditions, closes #15

### LINKED ISSUE #15: ] Criteria or Criteria?
[proposal]

I'm about to make an application that requires 1 criteria OR another criteria. I was thinking of an idea pushing a closure maybe?

```
$repository->pushCriteria(function ($apply)
{
  $apply(new WherePaidAndApprovedCriteria);
}, 'OR');

$repository->pushCriteria(function ($apply)
{
  $apply(new WhereAlwaysDisplayFlagCriteria);
}, 'OR');
```

### PR DESCRIPTION
**Pull request by bweston92**

### CODE REVIEW

**Comment by anlutro** [comment]
Good idea! A couple of comments.

`applyCriteria` can probably be made a bit simpler to prevent code duplication.

```php
$logic = (static::LOGIC_AND === $criteria[1] ? 'and' : 'or');

$query->whereNested(function ($inner) use ($criteria) {
	$inner->push($criteria);
}, $logic);
```

Also if you could switch to tabs instead of spaces and use PSR-2 style braces (no newline before braces in if/else/for/foreach/etc) that'd save me some work.

**Comment by bweston92** [comment]
Pushed

**Comment by bweston92** [comment]
@anlutro can you add a new tag when possible :)

**Comment by bweston92** [comment]
Do we want to nest the overall querying? Around the fore-each loop?

**Comment by anlutro** [comment]
That's probably something that should be done across all the criteria classes when I think about it.

Also I'm wondering if the logic (and/or) should to be moved to the constructor because you usually want to only use one or the other all the criteria, not switch between them from each `push()` call.

**Comment by bweston92** [comment]
I agree tottally!



—

**Comment by anlutro** [comment]
Tagged 0.7.8

**Pull request merged**
