### PR TITLE
Soft deleting Eloquent repository.

### PR DESCRIPTION
**Pull request by bweston92**

### CODE REVIEW

**Comment by anlutro** [comment]
This is a good idea. Could you change the `newQuery` method to use this structure instead?

```
query = parent::newQuery()
if (this.withTrashed) query.withTrashed()
if (this.onlyTrashed) query.onlyTrashed()
return query
```

**Comment by bweston92** [comment]
I can return the parent yes. Unfortunately I cannot call them methods without them being static and returning new queries.

**Comment by anlutro** [comment]
Are you sure? I thought the softdeleting scope thingy added macros to the model's query builder.

**Comment by bweston92** [comment]
They have to be called statically. https://github.com/laravel/framework/blob/4.2/src/Illuminate/Database/Eloquent/SoftDeletingTrait.php#L119

**Comment by anlutro** [comment]
`$query->withTrashed()` and `$query->withoutTrashed()` works fine in my local install at least.

I can't find the entire trace of how it works, but macros are being added to the builder here:

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Database/Eloquent/SoftDeletingScope.php#L116-L150

**Comment by bweston92** [comment]
Updated code to reflect what you said.

**Comment by anlutro** [comment]
Thanks! I'll look more at this later, I just realized that setting up tests for all versions of Laravel for this is going to be a challenge.

**Comment by bweston92** [comment]
Maybe we should only test one version (latest version)?

**Comment by anlutro** [comment]
That'd be nice, but I use this in 4.1 and 4.2 systems and don't plan on using 5.0 any time soon.

I think I'll just merge this as an undocumented feature and figure out the tests later.

Thanks!

**Pull request merged**
